global using Duende.IdentityServer;
global using Duende.IdentityServer.Models;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Walmart.Identity.DbContexts;
global using Walmart.Identity.Entities;
global using Walmart.Identity.Pages;
global using Walmart.Identity.Helpers;
